-- -- move to test
-- main :: IO ()
-- main = do 
--     Microtest.eq (Just "GDP") (getName title)
--     Microtest.eq (Just "rog") (getUnit title)
--     where 
--         title = "Gross domestic product, % change to previous period"
